View All Case Details
ONSdigital/census-rm-ops-ui pull request #4
Opened 2020-08-27 13:28 UTC by LeoKHoward

# Motivation and Context
Offers user ability to view all case and event details of selected case

# What has changed
New page to view all case details
New templates
Tests

# How to test?
Build case-api image and run ops-ui locally. Select a case and check you can see the details

# Links
https://trello.com/c/ZxxGq4aT/1222-r-ops-ui-view-all-case-details-13
https://rops-prototypes.netlify.app/prototypes/rops-management/version-2/1-acacia-avenue/index.html

2020-08-27 14:14 UTC, NickGrantONS requested changes
<img width="1316" alt="Screenshot 2020-08-27 at 15 12 38" src="https://user-images.githubusercontent.com/41681172/91453650-ee995580-e877-11ea-8077-04dce77fa664.png">

Can you pretty-print the JSON payload a bit to make it more readable?

2020-08-28 06:45 UTC, AdamHawtin commented on census_rm_ops_ui/templates/view_case_details.html
> +{% extends "layouts/base.html" %}
We've used 2 spaces indents on the other HTML templates, would be nice to format this one to match 💅

2020-08-28 06:47 UTC, AdamHawtin commented on census_rm_ops_ui/templates/view_case_details.html
> +            <p>{{ key }} : {{ value }}</p>
Could make this key bold the same as above. Normally leave a space after the colon not before too.

2020-08-28 06:48 UTC, AdamHawtin commented on census_rm_ops_ui/views/case_details.py
> +    case_details.pop('events')
`pop` returns the element it pops
```suggestion
    case_events = case_details.pop('events')
    sorted_case_events = sorted(case_events, key=lambda case_event: case_event['eventDate'])
```

2020-08-28 07:02 UTC, AdamHawtin requested changes
Couple of small bits

2020-08-28 12:32 UTC, NickGrantONS approved these changes
Very nice

2020-09-01 13:22 UTC, AdamHawtin approved these changes
👍 Perfectly functional first iteration, hoping we can get some UI help on this ASAP to turn it into a slightly more user-friendly page.

I think all it really needs is a bit of thought on the layout and to make the events section/details collapsible.

2020-09-02 07:54 UTC, merged