1223 R-ops UI Link a QID to a case
ONSdigital/census-rm-ops-ui pull request #5
Opened 2020-09-10 15:04 UTC by AdamHawtin

# Motivation and Context
We want to be able to link QID's to cases from the R-ops UI.

# What has changed
* Add link box to the case details page
* Add QID link confirmation page
* Add flash messages to confirm a link has been submitted or error if the QID does not exist

# How to test?
Build and run the AT's branch

# Links
https://trello.com/c/6QdthBHC/1223-r-ops-ui-link-a-qid-to-a-case-13

2020-09-15 06:11 UTC, NickGrantONS requested changes
Requires some audit logging that can be easily extracted/searched in the logs

2020-09-15 06:27 UTC, davidmort commented on census_rm_ops_ui/controllers/case_controller.py
> +    response = requests.put(f'{case_api_url}/qids/link', json=payload)
Should be creating and passing a transaction I'd to the API here, and we should be logging that transactionid out too along with the audit log (see @NickGrantONS comment)

2020-09-15 07:46 UTC, ryangrundy7 commented
> Requires some audit logging that can be easily extracted/searched in the logs

@NickGrantONS  The app does have audit logging for everything request that happens 
```
{"audit": true, "requestPath": "/case-details/link-qid/submit/?", "requestMethod": "POST", "user": "ryan.grundy@census.gov.uk", "level": "info", "severity": "info", "service": "census-rm-ops-ui", "created_at": "2020-09-15T07:32:36.440 │
│ 897"}
```

2020-09-16 08:46 UTC, NickGrantONS commented
> > Requires some audit logging that can be easily extracted/searched in the logs
> 
> @NickGrantONS The app does have audit logging for everything request that happens
> 
> ```
> {"audit": true, "requestPath": "/case-details/link-qid/submit/?", "requestMethod": "POST", "user": "ryan.grundy@census.gov.uk", "level": "info", "severity": "info", "service": "census-rm-ops-ui", "created_at": "2020-09-15T07:32:36.440 │
> │ 897"}
> ```

Needs the transaction ID of any messages which were emitted on a user's behalf, so that we have end-to-end audit trail

2020-09-18 08:34 UTC, liamtoozer approved these changes
LGTM 👍

2020-09-18 14:06 UTC, NickGrantONS approved these changes

2020-09-23 09:01 UTC, merged